### ISSUE TITLE
Error clic Button Options

### ISSUE THREAD

**Issue by jhofran** [OpenDBDiff/OpenDBDiff#43]
System.NullReferenceException: Referencia a objeto no establecida como instancia de un objeto.
   en OpenDBDiff.Schema.SQLServer.Generates.Options.SqlOption..ctor(IOption option) en C:\projects\opendbdiff\OpenDBDiff.Schema.SQLServer.Generates\Options\SqlOption.cs:línea 28
   en OpenDBDiff.Schema.SQLServer.Generates.Front.SqlOptionsFront.Load(IOption option) en C:\projects\opendbdiff\OpenDBDiff.Schema.SQLServer2005\Front\SqlOptionsFront.cs:línea 36
   en OpenDBDiff.Front.OptionForm.Show(IWin32Window owner, IOption filter) en C:\projects\opendbdiff\OpenDBDiff\Front\OptionForm.cs:línea 22
   en OpenDBDiff.Front.PrincipalForm.btnOptions_Click(Object sender, EventArgs e) en C:\projects\opendbdiff\OpenDBDiff\Front\PrincipalForm.cs:línea 483

**Comment by ironicnet** [comment]
Ok i was able to reproduce this:

1. Open the app
2. Press the option button.
3. Error appears

This only happens if you didn't execute a compare first. 
If you execute a compare first, you won't have any problem.

Regarding this, as far i'm aware the configuration of "Options" isn't working. see #1
