### ISSUE TITLE
Missing scripts when updating the Synchronization Script

### ISSUE THREAD

**Issue by ironicnet** [OpenDBDiff/OpenDBDiff#54]
When running a comparision, and going to the Synchronization Script. It shows several warnings of missing scripts.

Database script:
```SQL
USE master
GO
CREATE DATABASE DB1
GO
CREATE DATABASE DB2
GO
Use DB1
GO
create procedure TEST_PROC 
AS
Select 'Hello'
GO
USE Master
```

if we select the SynchronizationScript Tab and press "Compare", the SP has the creation script correctly.
if we change the Tabs, the creation script goes missing.

It seems that I introduced this bug in this commit: https://github.com/OpenDBDiff/OpenDBDiff/commit/9adbb8274f9e179d9c1b39c9407027694ce6e8fc#diff-bcd9b1ccce4e2821b2444e4cbf0ae426R125

I tested a little and it seems that it doesn't like the no "linq" style.
As far as i could debug, the "StoreProcedure" schema, thinks that it was already added to the diff script, so it doesn't add the create sql. Causing the missing script.

I have a PR almost ready, where all the SQL scripts are added to the SQLScriptList. And the SQLScriptList keeps track of which schema is already added and with which action.

I just wanted to notify of this bug.

**Comment by GaryWayneSmith** [comment]
I would be nice to see what warnings you were receiving before I also open a bug.  The older version opendbdiff was working beautifully for me until I migrated my development and production box to SQL Server 2016.  It appeared to work fine until recently when I started seeing errors like the ones below.  These were all PK creation scripts.  The problem is the drops were created properly but the create scripts failed (I'm sure you can understand the madness that ensued after ;) ).  Anyway, I'm trying to find out if this is a separate bug or potentially related to your warnings and errors.

--
-- DIFF-ERROR 0x00000040.004: Missing CreateStatus script for Constraint 'PK_yyy'
--


--
-- DIFF-ERROR 0x00000002.004: Missing AlterStatus script for Constraint 'PK_xxx_1'
--

**Comment by jspraul** [comment]
@GaryWayneSmith Thanks for reporting your experience in production! I apologize for the issues caused by missing constraints.

The transition to GitHub initially stepped away from the conservative versioning previously front-and-center on the CodePlex release system, but there should now be a clear split between development and a stable version.

Taking the specifics of your situation into account, I am going to recommend that promoting from dev to stable require a minimum amount of time/usage. However, this opens up a giant can of worms re:analytics that will be fun to work through.

**Comment by jspraul** [comment]
I will push this to both master and develop tomorrow.

Temporary work-around per @ironicnet: _**select the SynchronizationScript Tab [then] press "Compare"**_ ... then Ctrl+A, Ctrl+C copy the script out of the "Synchronized Script" tab to the clipboard.
