### ISSUE TITLE
Cleaning old result when firing new compare

### ISSUE THREAD

**Issue by kzelda** [OpenDBDiff/OpenDBDiff#65]
When i click compare button and when there are no diffrences , the old diff results isn't cleaned !

**Comment by igitur** [comment]
Please explain in more detail, giving exact steps to reproduce the problem.

**Comment by kzelda** [comment]
please clear components [txtNewObject , txtDiff , txtOldObject] when start a new compare operation

**Comment by igitur** [comment]
Please don't bark out orders. We're all sacrificing our private time to improve this project.

We don't want to blindly clear those components. Rather they should be refreshed according to the selected node in the treeview on the left.

So again, outline your steps carefully and thoughtfully, so that I can reproduce your problem and have a look at it.

**Comment by igitur** [comment]
Try the CI build at https://ci.appveyor.com/project/OpenDBDiff/opendbdiff/build/0.9.0.68/artifacts and let me know if it fixes the issue.

**Comment by jspraul** [comment]
I assume @kzelda updated their post to include the word "please", unfortunately GitHub doesn't make it obvious how to review the older comment versions, and searching reveals they [give zero ****s](https://github.com/dear-github/dear-github/issues/129).

In either case, thanks for taking the time to share this new feature. I "agree to disagree" with @igitur here; I appreciate his efforts improving this project, but I personally don't want to turn away useful feedback because of its tone. This is particularly true because internationally cultures approach this differently, English as a second language (often more like 4th or 5th) adds additional complexities, and text itself as a narrow-bandwidth communication medium all contribute to my complete inability to decipher anyone's true intent in written form. I will mention I appreciate @igitur's measured response explaining his preference, thanks for that.

Thanks again @kzelda for taking time to share your feedback here. I hope you've learned a bit about how the words chosen when communicating affect the likelihood of convincing someone else to help you.

https://news.ycombinator.com/item?id=16468196#16468879

**Comment by igitur** [comment]
It wasn't the tone. I got irritated because I explicitly asked for steps to reproduce the problem and the response was anything but that. If I'm going to steal time in-between my salaried job, I'd prefer to make it as little as possible and therefore people need to read what is being asked and give clear, but concise feedback.

**Comment by jspraul** [comment]
I've edited my comment. Knowing GitHub don't care, I've tried to do make what's changed clear.

Keep up the good work!

**Comment by kzelda** [comment]
Thank you very much for this useful project

**Comment by igitur** [comment]
@kzelda Try the CI build at https://ci.appveyor.com/project/OpenDBDiff/opendbdiff/build/0.9.0.68/artifacts and let me know if it fixes the issue.

**Comment by kzelda** [comment]
Hi @igitur, thx for your efforts , in this version when i compare , the left panel (tree) is always empty !

**Comment by igitur** [comment]
Well, for me to do anything more, I need explicit, detailed steps to reproduce the problem.
